package afm.analyzer.gui;

import afm.analyzer.measurements.AbstractMeasurement;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import org.apache.log4j.Logger;
import scaler.module.types.LengthUnit;

/**
 *
 * @author Drimal
 */
public class MeasurementRowPanel extends JPanel {

    private static final Logger logger = Logger.getLogger(MeasurementRowPanel.class);
    private List<AbstractMeasurement> selectedMeasurements;
    private AbstractMeasurement measurement;

    /**
     * Creates new form MeasurementJPanel
     * @param measurement
     * @param selectedMeasurements
     * @param enableOptions
     */
    public MeasurementRowPanel(AbstractMeasurement measurement,
            List<AbstractMeasurement> selectedMeasurements,
            boolean enableOptions) {
        initComponents();
        this.measurement = measurement;
        this.selectedMeasurements = selectedMeasurements;
        this.nameLabel.setText(measurement.getLabel());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        measurementGuiElement = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        checkBox = new javax.swing.JCheckBox();
        unitComboBox = new javax.swing.JComboBox();

        javax.swing.GroupLayout measurementGuiElementLayout = new javax.swing.GroupLayout(measurementGuiElement);
        measurementGuiElement.setLayout(measurementGuiElementLayout);
        measurementGuiElementLayout.setHorizontalGroup(
            measurementGuiElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );
        measurementGuiElementLayout.setVerticalGroup(
            measurementGuiElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nameLabel.setText("Default_Name");
        nameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nameLabel.setMaximumSize(new java.awt.Dimension(120, 14));
        nameLabel.setMinimumSize(new java.awt.Dimension(65, 14));

        checkBox.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxActionPerformed(evt);
            }
        });

        unitComboBox.setModel(new DefaultComboBoxModel(LengthUnit.retrieveAbbreviations()));
        unitComboBox.setSelectedIndex(5);
        unitComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                unitComboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(unitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBox)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(checkBox)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(unitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxActionPerformed
        manageMeasurementIntoSelectedMeasurements();
    }//GEN-LAST:event_checkBoxActionPerformed

    private void unitComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_unitComboBoxItemStateChanged
        String unit = (String) evt.getItem();
        measurement.setResultUnit(LengthUnit.parseFromAbbreviation(unit));
    }//GEN-LAST:event_unitComboBoxItemStateChanged

    private void manageMeasurementIntoSelectedMeasurements() {
        if (checkBox.isSelected()) {
            selectedMeasurements.add(measurement);
        } else {
            selectedMeasurements.remove(measurement);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JPanel measurementGuiElement;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JComboBox unitComboBox;
    // End of variables declaration//GEN-END:variables
}
