package afm.analyzer.gui;

import afm.analyzer.measurements.AbstractMeasurement;
import java.util.List;
import javax.swing.JPanel;

/**
 *
 * @author Drimal
 */
public class MeasurementRowPanel extends JPanel {

    private List<AbstractMeasurement> selectedMeasurements;
    private AbstractMeasurement measurement;

    /**
     * Creates new form MeasurementJPanel
     */
    public MeasurementRowPanel(AbstractMeasurement measurement, List<AbstractMeasurement> selectedMeasurements,
            boolean enableOptions) {
        initComponents();
        jButton1.setEnabled(enableOptions);
        this.measurement = measurement;
        this.selectedMeasurements = selectedMeasurements;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        measurementGuiElement = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        checkBox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout measurementGuiElementLayout = new javax.swing.GroupLayout(measurementGuiElement);
        measurementGuiElement.setLayout(measurementGuiElementLayout);
        measurementGuiElementLayout.setHorizontalGroup(
            measurementGuiElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );
        measurementGuiElementLayout.setVerticalGroup(
            measurementGuiElementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 39, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(0, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nameLabel.setText("Default_Name");
        nameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        checkBox.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Opt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBox)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(checkBox)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1)
                .addComponent(nameLabel))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxActionPerformed
        manageMeasurementIntoSelectedMeasurements();
    }//GEN-LAST:event_checkBoxActionPerformed

    private void manageMeasurementIntoSelectedMeasurements() {
        if (checkBox.isSelected()) {
            selectedMeasurements.add(measurement);
        } else {
            selectedMeasurements.remove(measurement);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel measurementGuiElement;
    private javax.swing.JLabel nameLabel;
    // End of variables declaration//GEN-END:variables
}
